name: CI

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo ::set-env name=VERSAO::$(grep version package.json|cut -d '"' -f4)
      - name: Test
        run: echo $VERSAO
