name: CI

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: get_version
        run: echo Hello world $TESTE
        env:
          TESTE: $( grep version package.json|cut -d '"' -f4 )
