name: CI

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: GITHUB_REF
      run: echo running on branch ${GITHUB_REF}
    - name: GITHUB_EVENT_NAME
      run: echo ${GITHUB_EVENT_NAME}
    - name: get version from package.json
      run: grep version package.json|cut -d '"' -f4