name: CI

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: get_version
        run: grep version package.json|cut -d '"' -f4
      - name: try to recovery version
        run: ${{ steps.get_version }}
      - name: try to recovery version outputs
        run: ${{ steps.get_version.outputs }}