name: CI

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Bump version and Push new tag
      uses: anothrNick/github-tag-action@1.18.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_TAG: v0.4.3
