name: Production

# on:
  # pull_request:
  #   branches: [master]
  #   types: [closed]
on:
  push:
    branches:
      - 'master'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: ./install.sh
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish package
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
