name: Production

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set env
        run: echo ::set-env name=VERSAO::$(grep version package.json|cut -d '"' -f4)
      - name: Test
        run: echo $VERSAO
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.18.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ VERSAO }}