name: Production

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Npm Install
        run: npm install --production
      - name: Publish package
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
