name: Publishing the TAG

on:
  pull_request:
    types: [closed]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: contains(github.ref, "release") && github.event.pull_request.merged == true
    steps:
      - name: Branch name 1
        run: echo running on branch ${GITHUB_REF}
      - name: Bump version and Push new tag
        uses: anothrNick/github-tag-action@1.18.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: v${GITHUB_REF}
