name: Publishing the TAG

on:
  pull_request:
    types: [closed]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: release value
        run: echo Branch contains release value  contains(github.ref, 'release')
      - name: event merged
        run: echo event merged github.event.pull_request.merged
      - name: Bump version and Push new tag
        uses: anothrNick/github-tag-action@1.18.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: v${GITHUB_REF}
